apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  hostPID: true
  hostNetwork: true
  serviceAccountName: test-sa
  containers:
  - name: test-pod
    image: k8s-arsenal-pod:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
    - name: cri-sock
      mountPath: /run/containerd/containerd.sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: cri-sock
    hostPath:
      path: /run/containerd/containerd.sock
